spring.data.mongodb.uri=mongodb+srv://1945musictrending_db_user:5BwEF4InAubGaw6i@mongostudy.nhqvzsf.mongodb.net/horse_racing_db?retryWrites=true&w=majority
spring.data.mongodb.database=horse_racing_db
logging.level.org.mongodb.driver=OFF
