spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/horse_racing_db}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:horse_racing_db}
logging.level.org.mongodb.driver=OFF